project_id = "ivzywojdudwsteiqtflx"

[functions.upload-video]
verify_jwt = false

[functions.record-view]
verify_jwt = false

[functions.request-payout]
verify_jwt = false

[functions.become-creator]
verify_jwt = false